### ISSUE TITLE
use valid rest urls and explain what is going on at the pages

### ISSUE THREAD

**Issue by Morriz** [jgravelle/AutoGroq#10]
Your single page app or whatever streamlit is doing can be given urls (pages) that will reflect the content in the address bar, allowing us to see what we are doing.

It is now not clear whether you allow to edit the main request in "Enter your request" when editing an agent config. By offering to edit the data there users might think its a copy that needs to be edited to get better results but when doing that it is actually the main input ;(

So please implement simple UX practices: one url to edit a resource (did NOT duplicate resources/form(parts) in other locations

**Comment by jgravelle** [comment]
It's all the same page, dude.  I'll try to do better.  Thanks...
