### ISSUE TITLE
CrewAI\Autogen Files Names

### ISSUE THREAD

**Issue by bamit99** [jgravelle/AutoGroq#12]
Not a major issue. The tool is working perfectly fine but when I saw the videos, I realized that the JSON files are named according to the role where as the ones that my setup create are just agent_0, agent_1, agent_2 and so on. Is it as intended or am I missing something?

**Comment by jgravelle** [comment]
You are correct. The Crew AI files don't yet have names.  On the TO DO,
though.

Thanks...

-jjg
