### ISSUE TITLE
ui_utils.py has extra args in call

### ISSUE THREAD

**Issue by beanlover** [jgravelle/AutoGroq#14]
line 197 - the call to "zip_files_in_memory" has 3 arguments and the method only accepts 1.

I changed the call to model the other calls in that same file and it seemed to work. 

I don't (yet) know how to make PRs in github so I thought I would just put this here.

**Comment by jgravelle** [comment]
Thanks, I'll check it out. If you can remember what you did to make that
happen, it'd help... -jjg

**Comment by beanlover** [comment]
I entered an initial prompt and agents were generated. I clicked the gear icon for one of the agents and added an input in the "enter your request" field and hit <enter> to send it. This is when the error happened.

After I updated the py code as noted above I went back and sent the same request from the same input and there was no error.

**Comment by jgravelle** [comment]
Found it.  Pushed a fix.  Thanks...!
