### ISSUE TITLE
html5lib Errors

### ISSUE THREAD

**Issue by arch3angel** [jgravelle/AutoGroq#15]
I attempted to run the application and got the following error related to html5lib

I have attempted to update html5lib without any errors but it still fails

I have uninstalled html5lib and then reinstalled it without any errors and it still failed

I am running this on Windows 10 currently

Any suggestions?

Here is the error:

PS D:\__AI-Projects\AutoGroq\AutoGroq> streamlit run .\main.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.126:8501

2024-05-17 22:47:20.577 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\\%USERNAME%\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "D:\__AI-Projects\AutoGroq\AutoGroq\main.py", line 6, in <module>
    from agent_management import display_agents
  File "D:\__AI-Projects\AutoGroq\AutoGroq\agent_management.py", line 8, in <module>
    from bs4 import BeautifulSoup
  File "C:\Users\\%USERNAME%\AppData\Local\Programs\Python\Python312\Lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Users\\%USERNAME%\AppData\Local\Programs\Python\Python312\Lib\site-packages\bs4\builder\__init__.py", line 314, in <module>
    from . import _html5lib
  File "C:\Users\\%USERNAME%\AppData\Local\Programs\Python\Python312\Lib\site-packages\bs4\builder\_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'. Did you mean: 'base'?
  Stopping...
PS D:\__AI-Projects\AutoGroq\AutoGroq>

**Comment by arch3angel** [comment]
As a quick update, I am adding the pip information for beautifulsoup4 and html5lib 

PS D:\__AI-Projects\AutoGroq\AutoGroq> pip show beautifulsoup4
Name: beautifulsoup4
Version: 4.4.0
Summary: Screen-scraping library
Home-page: http://www.crummy.com/software/BeautifulSoup/bs4/
Author: Leonard Richardson
Author-email: leonardr@segfault.org
License: MIT
Location: C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires:
Required-by: crewai-tools, embedchain, markdownify, unstructured

PS D:\__AI-Projects\AutoGroq\AutoGroq> pip show html5lib
Name: html5lib
Version: 1.1
Summary: HTML parser based on the WHATWG HTML specification
Home-page: https://github.com/html5lib/html5lib-python
Author:
Author-email:
License: MIT License
Location: C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: six, webencodings
Required-by: xhtml2pdf

**Comment by jgravelle** [comment]
Absolutely! This error indicates a compatibility issue between the html5lib library and the BeautifulSoup4 (bs4) library you're using. Here's the breakdown and how to fix it:

Understanding the Problem

BeautifulSoup4 is a powerful HTML and XML parsing library.
It often relies on html5lib for its parsing capabilities.
In a recent html5lib update (version 0.99999999 or later), they restructured their code, renaming some modules. This has caused compatibility problems with older versions of BeautifulSoup4.
Solutions

You have a few options to resolve this:

1. Downgrade html5lib (Simplest)

This is often the quickest fix:

pip install --upgrade html5lib==1.0b8
Use code [with caution.](https://github.com/faq#coding)

This will install an earlier version of html5lib that is compatible with your current BeautifulSoup4 installation.
2. Upgrade BeautifulSoup4 (Preferred)

This is a better long-term solution:

pip install --upgrade beautifulsoup4
Use code [with caution.](https://github.com/faq#coding)

This will update BeautifulSoup4 to the latest version, which is designed to work with the newer versions of html5lib.
3. Manual Patching (Not Recommended)

In some cases, you might see suggestions to manually edit the bs4 source code to account for the html5lib change. This is not recommended as it can lead to future problems and is less maintainable.
Steps

Try Option 1:

Open your terminal or command prompt.
Run pip install --upgrade html5lib==1.0b8
Restart your Streamlit app.
If Option 1 Fails, Try Option 2:

Run pip install --upgrade beautifulsoup4
Restart your Streamlit app.
Important Note: If you're working in a virtual environment, make sure it's activated before running the pip commands.

Why Upgrading is Better

Future Compatibility: Upgrading to the latest BeautifulSoup4 will make your code compatible with future html5lib updates.
Potential Improvements: Newer versions of libraries often include bug fixes, performance enhancements, and new features.
Example Code (After Fixing)

from bs4 import BeautifulSoup
import requests

url = "https://www.example.com"  # Replace with your URL
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html5lib')  # Explicitly use 'html5lib'

# Now you can parse and work with the soup object
Use code [with caution.](https://github.com/faq#coding)
play_circleeditcontent_copy
Troubleshooting Tips:

Clear Cache: If you're still encountering issues, clear your Streamlit cache by running streamlit cache clear.
Restart Kernel: If you're working in a Jupyter Notebook, restart the kernel.
Check Dependencies: Make sure all your project dependencies are up-to-date.
Please let me know if you have any other questions or need further assistance!

**Comment by arch3angel** [comment]
I executed the Option 2 and upgraded beautifulsoup4.  Everything works now!  THANK YOU!
