### ISSUE TITLE
How do I create agents?

### ISSUE THREAD

**Issue by scaruslooner** [jgravelle/AutoGroq#18]
I enter a request like "make a crm" and proceeds to make the re engineered prompt but not agents. 

![image](https://github.com/jgravelle/AutoGroq/assets/39450507/0421101d-3218-41d8-bab3-629454a005fe)

**Comment by jgravelle** [comment]
Thanks for the report.

Does it happen with every model?

**Comment by scaruslooner** [comment]
No, it only happens with llama 3 70b

**Comment by jgravelle** [comment]
That's Groq wackiness.  See the online demo notes on the welcome screen.  Thanks again... -jjg
