### ISSUE TITLE
No secrets files found!

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [jgravelle/AutoGroq#19]
I got this issue after pulling the latest version (6.6.6)

![image](https://github.com/jgravelle/AutoGroq/assets/22897462/267c72a2-7eef-4f13-8415-ce94f607688d)

**Comment by jgravelle** [comment]
Streamlit had an upgrade.  Might want to try:

pip install streamlit --upgrade

**Comment by jgravelle** [comment]
I was able to reproduce this.  Give me a few minutes for the fix...
