### ISSUE TITLE
Misconfiguration when using gpt-4o leads to gpt-4 being used

### ISSUE THREAD

**Issue by felipe-de-godoy** [jgravelle/AutoGroq#20]
When attempting to use the 'gpt-4o' parameter, the system still uses 'gpt-4'.

**Comment by jgravelle** [comment]
Boa descoberta!

You've actually unearthed a much larger problem.  With the multi-model scheme, that entire section should probably be unique to each provider.  I'm on it.  Thanks...

**Comment by felipe-de-godoy** [comment]
I made a pull request correcting some parameters that were frozen in 'gpt-4', and fixed it for me (at least in open ai billing lol)
