### ISSUE TITLE
style.css Error

### ISSUE THREAD

**Issue by arch3angel** [jgravelle/AutoGroq#23]
After running the application we get this following error at the top of the web browser screen above GROQ API Key

CSS file not found: D:__AI-Projects\AutoGroq\AutoGroq\AutoGroq\style.css

I believe it is looking for the style.css in the wrong location as it is stored within the project here:

D:__AI-Projects\AutoGroq\AutoGroq\style.css

**Comment by felipe-de-godoy** [comment]
When I tried the first time this error appeared. 

But the error hasn't displayed for me since the creation and activation of the venv with the requirements.
