### ISSUE TITLE
Agent Issue With AutoGen Studio

### ISSUE THREAD

**Issue by arch3angel** [jgravelle/AutoGroq#26]
Hello,

Everything generates in AutoGroq fine, imports into AutoGen database just fine.  I change the LLM to a local LLM running on LMStudio.  Everytime I try to run the agents and workflow generated by AutoGroq I get an API key error, if I manually generate the agents it works fine.

Any suggestions?

Thank you!

![API-Key-Error](https://github.com/jgravelle/AutoGroq/assets/3674499/4082e0ec-28b4-46ef-82dc-18c645c5b9cf)

**Comment by gxgl** [comment]
Hi,

I had the same issue. I didn't looked deeper to see the problem, but it looks like the setting in autogenstudio is not overwriting the model in agent so I have edited the files with gpt-4o (replaced the mistral model - in my case) and also the max_tokens value which for gpt-4o should be 4096 and then reimported the files.

I hope this will help you.

All the best,
George

**Comment by arch3angel** [comment]
> Hi,
> 
> I had the same issue. I didn't looked deeper to see the problem, but it looks like the setting in autogenstudio is not overwriting the model in agent so I have edited the files with gpt-4o (replaced the mistral model - in my case) and also the max_tokens value which for gpt-4o should be 4096 and then reimported the files.
> 
> I hope this will help you.
> 
> All the best, George

Can you show me an example of what you changed and where?

**Comment by jgravelle** [comment]
Yep.  That's exactly what I'm doing here:
https://www.youtube.com/watch?v=IlTovnAqMqM&t=85s

I need to add the ability to specify models rather than taking the Autogen
default.  Probably per agent...   -jjg

**Comment by gxgl** [comment]
Hi @arch3angel,

sure thing.

After you download and extract the files into a folder:

1.  Right click on that folder and open it in VSCode or any other editor that supports multi file search and replace and you will end up with something like this: 
![image](https://github.com/jgravelle/AutoGroq/assets/11505258/97ce2a07-fc06-4542-ba10-165eeb274328)
Then open an agent file (doesn't matter which one) and look for "model" and note the used model (example: "model": "mixtral-8x7b-32768", next look for "max_tokens" (example: "max_tokens": 32768) and note the values of these two.
Example in a file:
![image](https://github.com/jgravelle/AutoGroq/assets/11505258/52a1bef6-c558-4fbd-9609-0117f0d3203b)

2. Click on the magnification glass (search) if you use VSCode else you need to figure it out yourself how your preferred editor works and you will have a screen like this:
![image](https://github.com/jgravelle/AutoGroq/assets/11505258/f74d66aa-1b58-498c-af40-447ce7cf1e85)

- Now put in "Search" field mixtral-8x7b-32768 and gpt-4o in "Replace" field and it will show somehow near to this:
![image](https://github.com/jgravelle/AutoGroq/assets/11505258/06e3ecfa-3ce6-4347-91d4-92803a147a72)
...and if looks fine to you, then click on "Replace All" button near to "Replace" field in the right (marked by red sqaure in the next image).
![image](https://github.com/jgravelle/AutoGroq/assets/11505258/bb88db3a-5dc2-499f-b1cf-9ce307e4255e)
- Repeat the step for the max_tokens value if is the case - *For gpt-4o it must be 4096*:
![image](https://github.com/jgravelle/AutoGroq/assets/11505258/9acb7184-4bc1-4d2d-94f7-c50bb3855c0c)

At the end it will look like this:
![image](https://github.com/jgravelle/AutoGroq/assets/11505258/5b019d47-292e-42de-9d5d-5259d56f3657)
...now save all files and that's all. I think...

I hope this helps.

All the best,
George

**Comment by jgravelle** [comment]
Alright, people.  Click on any agent's gear icon and you'll see you can set any model listed in the config.py

If you don't select any, the current main dropdown selection will be used by default.  AND you can change all agents at once.

Hope this makes things nicer...


-jjg
