### ISSUE TITLE
use gitignore for compiled python etc

### ISSUE THREAD

**Issue by scruffynerf** [jgravelle/AutoGroq#29]
It's a best practice to use .gitignore to remove the pycache directories, which are both autocreated, and user specific (version, machine, etc etc)

Also, provide a sample config file to copy before first use, and remove the actual config from the repo, otherwise any git update balks due to file changes made to that config file.

**Comment by jgravelle** [comment]
Thanks for the tip!  I'm on it... -jjg

**Comment by jgravelle** [comment]
Had to meet you half way.  Streamlit immediately digests GitHub updates, so a valid config.py is mandatory.  Thanks again...

**Comment by scruffynerf** [comment]
You should delete the existing __pycache__ folders (there are 3 I think)

**Comment by jgravelle** [comment]
Four.  Got 'em.  Thanks...


-jjg
