### ISSUE TITLE
Error making API request: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by shaunstoltz** [jgravelle/AutoGroq#3]
Getting this error when first trying to generate agents:

Error making API request: 'str' object has no attribute 'get'
Debug: AutoGen Agents: []
Debug: CrewAI Agents: []
Error: No agents created.

**Comment by shaunstoltz** [comment]
Ahah, very good, yes... it works now. Thanks!

**Comment by jgravelle** [comment]
My bad.  I should make the 70b the default.  Next release...
