### ISSUE TITLE
Move the creation Prompts used to allow user changes

### ISSUE THREAD

**Issue by scruffynerf** [jgravelle/AutoGroq#30]
The various prompts actually used (the skills, the agents, etc etc) should be in at least a user config file so it can be edited and/or add some UI to edit and save.

And while on the topic, using 'Autogen Studio python skill' in the skill creation prompt gets better results than 'python skill', and giving an example showing the format (which autogen actually can (and does?) read for context) helps with ensuring the formatting is correct, and comments and arguments are correctly spec'ed

**Comment by jgravelle** [comment]
Thanks again!  I've divorced the prompts from their surrounding code...
