### ISSUE TITLE
you really need to fix the config.py problem

### ISSUE THREAD

**Issue by scruffynerf** [jgravelle/AutoGroq#32]
https://github.com/jgravelle/AutoGroq/commit/81bffd9738e468b80ad2b1d18cd133835bb916b5

you reverted the autogen db location back to your personal config.

PLEASE, fix the config.py problem.  There are ways to make it work with streamlit.
The config.py should _either_ be user changed and NOT in the repo, or in the repo, and get values from some other file, NOT in the repo.  The moment the user changes the config.py, the next time (and every time) they gitpull, they have a problem they have to deal with.

**Comment by jgravelle** [comment]
I really need to?

Okay, I'll get right on it, boss...

**Comment by scruffynerf** [comment]
> I really need to? Okay, I'll get right on it, boss...

When the main dev himself is bit by the issue (did you really intend to revert from a working bit of code to a fixed path useful only to you? Why?), and every single user who attempts an upgrade to the latest code via `git pull`, gets an error and is blocked because they modified the config.py which is wrongly _in_ the repo despite it expects user edits by design, and so git pull can NEVER work in that manner, and the issue was raised previously but you rejected solving it because you use it as is for the online demo, then yes, 'you really need to'.  Or hey, ignore someone actually giving you feedback.  Up to you.

**Comment by jgravelle** [comment]
I'm not ignoring you and I value your feedback.

I'm also giving you the benefit of the doubt regarding your abruptness.  Could be a language thing.  Maybe inadequate pharmaceuticals are to blame.  Whatever.  

We'll be cool if we can continue to ASK things of one another and take care not to demand them.  As I said, I'm on it...

**Comment by scruffynerf** [comment]
Yes, I'd asked once in a previous issue, and it was rejected as mentioned, so I said 'you really need to' and explained why, to express that rejection again wasn't appropriate.  That's not a demand, but I can see how you took it that way.  No harm, moving on.

**Comment by jgravelle** [comment]
## Configuration

To customize the configurations for your local environment, follow these steps:

1. Create a new file called `config_local.py` in the same directory as `config.py`.
2. Copy the contents of `config_local_example.py` into `config_local.py`.
3. Modify the values in `config_local.py` according to your specific setup, such as API keys and URLs.
4. Save the `config_local.py` file.

Note: The `config_local.py` file is not tracked by Git, so your customizations will not be overwritten when pulling updates from the repository.

**Comment by scruffynerf** [comment]
thanks for the shoutout in the video, @jgravelle
