### ISSUE TITLE
Skills versus Tools?

### ISSUE THREAD

**Issue by scruffynerf** [jgravelle/AutoGroq#33]
I'm confused on how you are using Skills vs Tools.  While you prompt for both, and make json for both...
Skills are specific _files_ of python code, to do 'this action'.
Tools are used by OpenAI, to do 'this action'
But in the actual  Autogen Studio code, 'tools' are used to call _skills_.

This seems redundant, and I'm curious if why we need both created.  Skills is the right answer, "tools" is only how skills get called in the final code.

(I'm trying to write a better set of prompts)

**Comment by jgravelle** [comment]
This is where Autogen kind of diverges from the SOP of other agent
architectures by conflating the two.

The de facto standard is that 'tools' are single-purpose:
retrieve_html(url), html_to_markup(html), etc.
...whereas skills are the next higher operational level that uses skills:
get_website_as_markup(), for example, could call both the aforementioned
'tools'.

A simpler real-world analogy is:  hammer is a tool, carpentry is a skill.

While AutoGroq™ was originally intended to be Autogen and Groq specific,
the user base has insisted upon a wider scope of operations.  So
placeholders for both skills and tools have been accounted for...


-jjg
