### ISSUE TITLE
headsup: newest autogenstudio changes the db tables

### ISSUE THREAD

**Issue by scruffynerf** [jgravelle/AutoGroq#37]
@jgravelle in trying to track down a bug in AutogenStudio, I updated to the very latest code

https://pypi.org/project/autogenstudio/0.0.56rc12/
`pip install autogenstudio==0.0.56rc12`

ignore that current code claims to be 0.0.56, but is dated March 21st, the above is May30th

This stuff is all related to the new changes from this issue:
https://github.com/microsoft/autogen/pull/2425
which went live _3 weeks_ ago, but the code hasn't been updated for pip/etc yet (due to the version issue above)

The database.sqlite tables changed, which confused the hell out of me, cause the old tables were there, but unused. (ie autogenstudio suddenly lost all of my data, but it was in db still)

Tables changed quite a bit, not merely the names (which went from multiples like `skills` to `skill`) so you'll have to change it all soonish.

Best answer: unless they write a conversion from old to new, export everything to json files and then blow your old db away (or move/rename it, if you don't live on the edge), and then update and run autogenstudio and let it make the new db with just the new tables.  The effect of running the new code with a older DB is it makes a mess, and you end up both old and new tables.

**Comment by jgravelle** [comment]
Well, I mean, if I'll HAVE to... 😎


-jjg

**Comment by scruffynerf** [comment]
Suggestion (I'm working thru the above needed changes and doing research into improvements):

I've been having issues with the autogen chatgroup not correctly handling the workflow of who should be next, etc.

Looking at https://microsoft.github.io/autogen/blog/2023/12/29/AgentDescriptions
The description field of the agent should be an objective ("this agent is", not "you are") short idea/summary the workflow mod can use to decide who to call on.  It defaults to the system message, which is bad, as that's usually 'You are' style prompts.

Your autogroq moderator bot is similar.

**Comment by jgravelle** [comment]
> Looking at https://microsoft.github.io/autogen/blog/2023/12/29/AgentDescriptions The description field of the agent should be an objective ("this agent is", not "you are") ...

Good call.  Done...  -jjg

**Comment by scruffynerf** [comment]
> Good call. Done... -jjg

Um, not sure that's right (given the commit I just saw to the prompts)... will discuss.  It's important to realize that "system prompt" is the prompt for the model "You are..." and prompts the LLM to do XYZ tasks, but description should be a simple summary like "This agent, XYZ doer, is responsible for X, Y, and Z tasks."

I'm trying to work on pieces so I can do separate PRs, so you making changes to main branch is a bit difficult.  Hazards of one dev vs inviting others to help.

**Comment by jgravelle** [comment]
If the impact turns out to be negative, I'll roll it back.  In beta, every
user is a g̶u̶i̶n̶e̶a̶ p̶i̶g̶  quality control analyst...
