### ISSUE TITLE
ImportError: cannot import name 'getStringIO' from 'reportlab.lib.utils

### ISSUE THREAD

**Issue by jsarsoun** [jgravelle/AutoGroq#40]
pulled the latest commit. This is the error I get when running main.py

 File "C:\Users\jsars\anaconda3\envs\AutoGroq\Lib\site-packages\xhtml2pdf\xhtml2pdf_reportlab.py", line 20, in <module>
    from reportlab.lib.utils import flatten, open_for_read, getStringIO, \
ImportError: cannot import name 'getStringIO' from 'reportlab.lib.utils' (C:\Users\jsars\anaconda3\envs\AutoGroq\Lib\site-packages\reportlab\lib\utils.py)

**Comment by jgravelle** [comment]
Yeah, we had issues.  Should be resolved now...

-jjg
