### ISSUE TITLE
Auto-moderate only seems to work for 2-3 Agent

### ISSUE THREAD

**Issue by LiquidMovz** [jgravelle/AutoGroq#43]
Auto-moderate only seems to work for 2-3 Agent as far as adding Additional Inputs. Is this the expected behavior? It would be great to have all the agents instructing the next agent on what to do, rather than just stating what they plan to do themselves.

**Comment by jgravelle** [comment]
Yep.  Moderator Bot needs work.  Thanks...  -jjg
