### ISSUE TITLE
Feature Request: drop down menu for LLM provider and models

### ISSUE THREAD

**Issue by HyperUpscale** [jgravelle/AutoGroq#46]
I just checked the code briefly, but I don't understand why the provider and models are hardcoded.

Would be much better and way more elegant if there is a drop down menu, that will allow to switch between the Providers and the models to be obtained from the available ones.

Currently those are hardcoded... we need to manually edit and then run the server again ...

**Comment by elwc-edge** [comment]
💯 @HyperUpscale, dropdown for LLM providers and models would be 🔥 way better than hardcoding. Makes the app way easier to use. @jgravelle, what do you think?

**Comment by jgravelle** [comment]
I don't disagree with any of that...   https://discord.gg/DXjFPX84gs

**Comment by jgravelle** [comment]
Did...
